/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang");
        mycode.tampilDataSatuan(tabelSatuan, "SELECT*FROM satuan");
        mycode.tampilDataPesanan(tabelPesanan, "SELECT*FROM pesanan");
        mycode.tampilDataRiwayat(tabelRiwayat, "SELECT*FROM riwayat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlSatuan = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNamaSatuan = new javax.swing.JTextField();
        txtKodeSatuan = new javax.swing.JTextField();
        btnHpsSatuan = new javax.swing.JButton();
        btnSmpnSatuan = new javax.swing.JButton();
        btnUbhSatuan = new javax.swing.JButton();
        txtCariSatuan = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelSatuan = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdSatuan = new javax.swing.JTextField();
        pnlBarang = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtKeteranganBarang = new javax.swing.JTextField();
        txtCariBarang = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtStokAwal = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnUbhBarang = new javax.swing.JButton();
        btnHpsBarang = new javax.swing.JButton();
        btnSmpnBarang = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtStatusBarang = new javax.swing.JTextField();
        txtRekomendasiBarang = new javax.swing.JTextField();
        txtAdminView = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtSatuanId_Brg = new javax.swing.JTextField();
        txtStafView = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtTanggalUpdate = new javax.swing.JTextField();
        pnlRiwayat = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtBarangId_Rw = new javax.swing.JTextField();
        txtUserId_Rw = new javax.swing.JTextField();
        txtJenisRiwayat = new javax.swing.JTextField();
        btnHpsRIwayat = new javax.swing.JButton();
        btnSmpnRiwayat = new javax.swing.JButton();
        btnUbhRiwayat = new javax.swing.JButton();
        txtCariRiwayat = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelRiwayat = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtIdRiwayat = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtKeteranganRiwayat = new javax.swing.JTextField();
        txtQtyRiwayat = new javax.swing.JTextField();
        txtTanggalRiwayat = new javax.swing.JTextField();
        pnlPesanan = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtStafId = new javax.swing.JTextField();
        txtMarketingId = new javax.swing.JTextField();
        txtBarangId_Psn = new javax.swing.JTextField();
        btnHpsPesanan = new javax.swing.JButton();
        btnSmpnPesanan = new javax.swing.JButton();
        btnUbhPesanan = new javax.swing.JButton();
        txtCariPesanan = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelPesanan = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtIdPesanan = new javax.swing.JTextField();
        txtTanggalKirim = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtTanggalMinta = new javax.swing.JTextField();
        txtPermintaan = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtRekomendasiPesanan = new javax.swing.JTextField();
        txtStatusPesanan = new javax.swing.JTextField();
        txtStatusRekomendasi = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtPengiriman = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnSatuan = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnPesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlSatuan.setBackground(new java.awt.Color(204, 204, 204));
        pnlSatuan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nama ");
        pnlSatuan.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Kode ");
        pnlSatuan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNamaSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaSatuan.setForeground(new java.awt.Color(0, 0, 0));
        pnlSatuan.add(txtNamaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtKodeSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtKodeSatuan.setForeground(new java.awt.Color(0, 0, 0));
        pnlSatuan.add(txtKodeSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsSatuan.setText("HAPUS");
        btnHpsSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsSatuanActionPerformed(evt);
            }
        });
        pnlSatuan.add(btnHpsSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 90, -1));

        btnSmpnSatuan.setText("SIMPAN");
        btnSmpnSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnSatuanActionPerformed(evt);
            }
        });
        pnlSatuan.add(btnSmpnSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 90, -1));

        btnUbhSatuan.setText("UBAH");
        btnUbhSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhSatuanActionPerformed(evt);
            }
        });
        pnlSatuan.add(btnUbhSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, -1));

        txtCariSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariSatuan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariSatuanKeyReleased(evt);
            }
        });
        pnlSatuan.add(txtCariSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, -1));

        tabelSatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelSatuan);

        pnlSatuan.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 490, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Satuan");
        pnlSatuan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdSatuan.setForeground(new java.awt.Color(0, 0, 0));
        pnlSatuan.add(txtIdSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlSatuan, "card4");

        pnlBarang.setBackground(new java.awt.Color(204, 204, 204));
        pnlBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Keterangan");
        pnlBarang.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Nama");
        pnlBarang.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Kode ");
        pnlBarang.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtKodeBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtKodeBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtKeteranganBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtKeteranganBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        txtCariBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtCariBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyReleased(evt);
            }
        });
        pnlBarang.add(txtCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelBarang);

        pnlBarang.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 770, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Barang");
        pnlBarang.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtStokAwal.setBackground(new java.awt.Color(255, 255, 255));
        txtStokAwal.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtStokAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Stok Awal");
        pnlBarang.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 90, -1));

        btnUbhBarang.setText("UBAH");
        btnUbhBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhBarangActionPerformed(evt);
            }
        });
        pnlBarang.add(btnUbhBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 100, 30));

        btnHpsBarang.setText("HAPUS");
        btnHpsBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsBarangActionPerformed(evt);
            }
        });
        pnlBarang.add(btnHpsBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 100, 30));

        btnSmpnBarang.setText("SIMPAN");
        btnSmpnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnBarangActionPerformed(evt);
            }
        });
        pnlBarang.add(btnSmpnBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 100, 30));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Stok");
        pnlBarang.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, -1));

        txtStok.setBackground(new java.awt.Color(255, 255, 255));
        txtStok.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Admin View");
        pnlBarang.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 100, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Status");
        pnlBarang.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, -1));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Rekomendasi");
        pnlBarang.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        txtStatusBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtStatusBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 220, -1));

        txtRekomendasiBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtRekomendasiBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtRekomendasiBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 220, -1));

        txtAdminView.setBackground(new java.awt.Color(255, 255, 255));
        txtAdminView.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtAdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 220, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("ID Satuan");
        pnlBarang.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        txtSatuanId_Brg.setBackground(new java.awt.Color(255, 255, 255));
        txtSatuanId_Brg.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtSatuanId_Brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 220, -1));

        txtStafView.setBackground(new java.awt.Color(255, 255, 255));
        txtStafView.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtStafView, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 220, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Staf View");
        pnlBarang.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 90, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Tanggal Update");
        pnlBarang.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 140, -1));

        txtTanggalUpdate.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalUpdate.setForeground(new java.awt.Color(0, 0, 0));
        pnlBarang.add(txtTanggalUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 220, -1));

        Content.add(pnlBarang, "card3");

        pnlRiwayat.setBackground(new java.awt.Color(204, 204, 204));
        pnlRiwayat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Jenis ");
        pnlRiwayat.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("ID Barang");
        pnlRiwayat.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("ID User");
        pnlRiwayat.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtBarangId_Rw.setBackground(new java.awt.Color(255, 255, 255));
        txtBarangId_Rw.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtBarangId_Rw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtUserId_Rw.setBackground(new java.awt.Color(255, 255, 255));
        txtUserId_Rw.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtUserId_Rw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtJenisRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtJenisRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsRIwayat.setText("HAPUS");
        btnHpsRIwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsRIwayatActionPerformed(evt);
            }
        });
        pnlRiwayat.add(btnHpsRIwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, -1));

        btnSmpnRiwayat.setText("SIMPAN");
        btnSmpnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnRiwayatActionPerformed(evt);
            }
        });
        pnlRiwayat.add(btnSmpnRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 90, -1));

        btnUbhRiwayat.setText("UBAH");
        btnUbhRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhRiwayatActionPerformed(evt);
            }
        });
        pnlRiwayat.add(btnUbhRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, -1));

        txtCariRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtCariRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        txtCariRiwayat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariRiwayatKeyReleased(evt);
            }
        });
        pnlRiwayat.add(txtCariRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelRiwayat);

        pnlRiwayat.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 480, 155));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ID Riwayat");
        pnlRiwayat.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtIdRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtIdRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Tanggal");
        pnlRiwayat.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Keterangan");
        pnlRiwayat.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Quantity");
        pnlRiwayat.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtKeteranganRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtKeteranganRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        txtQtyRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtQtyRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        txtTanggalRiwayat.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        pnlRiwayat.add(txtTanggalRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));

        Content.add(pnlRiwayat, "card5");

        pnlPesanan.setBackground(new java.awt.Color(204, 204, 204));
        pnlPesanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("ID Barang");
        pnlPesanan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("ID Staf");
        pnlPesanan.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("ID Marketing");
        pnlPesanan.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtStafId.setBackground(new java.awt.Color(255, 255, 255));
        txtStafId.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtStafId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtMarketingId.setBackground(new java.awt.Color(255, 255, 255));
        txtMarketingId.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtMarketingId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtBarangId_Psn.setBackground(new java.awt.Color(255, 255, 255));
        txtBarangId_Psn.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtBarangId_Psn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsPesanan.setText("HAPUS");
        btnHpsPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPesananActionPerformed(evt);
            }
        });
        pnlPesanan.add(btnHpsPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 90, 30));

        btnSmpnPesanan.setText("SIMPAN");
        btnSmpnPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPesananActionPerformed(evt);
            }
        });
        pnlPesanan.add(btnSmpnPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, 30));

        btnUbhPesanan.setText("UBAH");
        btnUbhPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPesananActionPerformed(evt);
            }
        });
        pnlPesanan.add(btnUbhPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, 30));

        txtCariPesanan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPesanan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPesananKeyReleased(evt);
            }
        });
        pnlPesanan.add(txtCariPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 370, -1));

        tabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelPesanan);

        pnlPesanan.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 800, 180));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ID Pesanan");
        pnlPesanan.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdPesanan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPesanan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtIdPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtTanggalKirim.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKirim.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtTanggalKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 220, -1));

        jLabel38.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Tanggal Kirim");
        pnlPesanan.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 130, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Tanggal Minta");
        pnlPesanan.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, -1));

        txtTanggalMinta.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalMinta.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtTanggalMinta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 220, -1));

        txtPermintaan.setBackground(new java.awt.Color(255, 255, 255));
        txtPermintaan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtPermintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Permintaan");
        pnlPesanan.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Status Rekomendasi");
        pnlPesanan.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 180, -1));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Rekomendasi");
        pnlPesanan.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 110, -1));

        jLabel52.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Status Pesanan ");
        pnlPesanan.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        txtRekomendasiPesanan.setBackground(new java.awt.Color(255, 255, 255));
        txtRekomendasiPesanan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtRekomendasiPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 220, -1));

        txtStatusPesanan.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusPesanan.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtStatusPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 220, -1));

        txtStatusRekomendasi.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusRekomendasi.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtStatusRekomendasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 220, -1));

        jLabel53.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Pengiriman");
        pnlPesanan.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, -1));

        txtPengiriman.setBackground(new java.awt.Color(255, 255, 255));
        txtPengiriman.setForeground(new java.awt.Color(0, 0, 0));
        pnlPesanan.add(txtPengiriman, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 220, -1));

        Content.add(pnlPesanan, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI MANAJEMEN ALAT TULIS KANTOR");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(102, 102, 102));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnSatuan.setBackground(new java.awt.Color(204, 204, 204));
        btnSatuan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSatuan.setForeground(new java.awt.Color(0, 0, 0));
        btnSatuan.setText("SATUAN");
        btnSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatuanActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(204, 204, 204));
        btnBarang.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnBarang.setText("BARANG");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnRiwayat.setBackground(new java.awt.Color(204, 204, 204));
        btnRiwayat.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRiwayat.setForeground(new java.awt.Color(0, 0, 0));
        btnRiwayat.setText("RIWAYAT");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPesanan.setBackground(new java.awt.Color(204, 204, 204));
        btnPesanan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPesanan.setForeground(new java.awt.Color(0, 0, 0));
        btnPesanan.setText("PESANAN");
        btnPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBarang)
            .addComponent(btnSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnRiwayat, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnPesanan, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBarang, btnPesanan, btnRiwayat, btnSatuan});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBarang)
                .addGap(18, 18, 18)
                .addComponent(btnRiwayat)
                .addGap(18, 18, 18)
                .addComponent(btnPesanan)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBarang, btnPesanan, btnRiwayat, btnSatuan});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatuanActionPerformed
        Content.removeAll(); 
        Content.add(pnlSatuan);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnSatuanActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        Content.removeAll(); 
        Content.add(pnlBarang);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        Content.removeAll(); 
        Content.add(pnlRiwayat);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananActionPerformed
        Content.removeAll(); 
        Content.add(pnlPesanan);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnPesananActionPerformed

    private void txtCariSatuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSatuanKeyReleased
        String c = txtCariSatuan.getText();
        String cari = "SELECT*FROM Satuan WHERE id LIKE '%"+c+"%'"+
                      "OR kode LIKE '%"+c+"%' OR nama LIKE '%"+c+"%'";
        mycode.tampilDataSatuan(tabelSatuan, cari);
    }//GEN-LAST:event_txtCariSatuanKeyReleased

    private void btnUbhSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhSatuanActionPerformed
        try {
            mycode.ubahSatuan(txtIdSatuan.getText(), txtKodeSatuan.getText(),
                              txtNamaSatuan.getText());

            mycode.tampilDataSatuan(tabelSatuan, "SELECT*FROM Satuan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhSatuanActionPerformed

    private void btnSmpnSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnSatuanActionPerformed
        try {
            if(txtIdSatuan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdSatuan.requestFocus();
            } else if(txtKodeSatuan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Kode Belum Diisi");
                txtKodeSatuan.requestFocus();
            } else if(txtNamaSatuan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaSatuan.requestFocus();
            } else {
                mycode.simpanSatuan02(txtIdSatuan.getText(), txtKodeSatuan.getText(),
                                      txtNamaSatuan.getText());

                mycode.tampilDataSatuan(tabelSatuan, "SELECT*FROM Satuan");

                if (mycode.duplikasi == true){
                    txtKodeSatuan.setText(mycode.CEK_KODE_SATUAN);
                    txtNamaSatuan.setText(mycode.CEK_NAMA_SATUAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnSatuanActionPerformed

    private void btnHpsSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsSatuanActionPerformed
        try {
            mycode.hapusSatuan(txtIdSatuan.getText());
            mycode.tampilDataSatuan(tabelSatuan, "SELECT*FROM Satuan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsSatuanActionPerformed

    private void txtCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyReleased
        String c = txtCariBarang.getText();
        String cari = "SELECT*FROM barang WHERE id LIKE '%"+c+"%'"+
                      "OR kode LIKE '%"+c+"%' OR nama LIKE '%"+c+"%'"+
                      "OR satuan_id LIKE '%"+c+"%' OR status LIKE '%"+c+"%'";
        mycode.tampilDataBarang(tabelBarang, cari);
    }//GEN-LAST:event_txtCariBarangKeyReleased

    private void btnHpsRIwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsRIwayatActionPerformed
        try {
            mycode.hapusRiwayat(txtIdRiwayat.getText());
            mycode.tampilDataRiwayat(tabelRiwayat, "SELECT*FROM Riwayat");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsRIwayatActionPerformed

    private void btnSmpnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnRiwayatActionPerformed
        try {
            if(txtIdRiwayat.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdRiwayat.requestFocus();
            } else if(txtUserId_Rw.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "User ID Belum Diisi");
                txtUserId_Rw.requestFocus();
            } else if(txtBarangId_Rw.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Barang ID Belum Diisi");
                txtBarangId_Rw.requestFocus();
            } else if(txtJenisRiwayat.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Jenis Belum Diisi");
                txtJenisRiwayat.requestFocus();
            } else if(txtQtyRiwayat.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Qty Belum Diisi");
                txtQtyRiwayat.requestFocus();
            } else if(txtKeteranganRiwayat.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKeteranganRiwayat.requestFocus();
            } else if(txtTanggalRiwayat.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Tanggal Belum Diisi");
                txtTanggalRiwayat.requestFocus();
            } else {
                mycode.simpanRiwayat02(txtIdRiwayat.getText(), txtUserId_Rw.getText(),
                                       txtBarangId_Rw.getText(), txtJenisRiwayat.getText(),
                                       txtQtyRiwayat.getText(), txtKeteranganRiwayat.getText(),
                                       txtTanggalRiwayat.getText());

                mycode.tampilDataRiwayat(tabelRiwayat, "SELECT*FROM Riwayat");

                if (mycode.duplikasi == true){
                    txtUserId_Rw.setText(mycode.CEK_USER_ID_RW);
                    txtBarangId_Rw.setText(mycode.CEK_BARANG_ID_RW);
                    txtJenisRiwayat.setText(mycode.CEK_JENIS_RW);
                    txtQtyRiwayat.setText(mycode.CEK_QTY_RW);
                    txtKeteranganRiwayat.setText(mycode.CEK_KETERANGAN_RW);
                    txtTanggalRiwayat.setText(mycode.CEK_TANGGAL_RW);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnRiwayatActionPerformed

    private void btnUbhRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhRiwayatActionPerformed
        try {
            mycode.ubahRiwayat(txtIdRiwayat.getText(), txtUserId_Rw.getText(),
                               txtBarangId_Rw.getText(), txtJenisRiwayat.getText(),
                               txtQtyRiwayat.getText(), txtKeteranganRiwayat.getText(),
                               txtTanggalRiwayat.getText());

            mycode.tampilDataRiwayat(tabelRiwayat, "SELECT*FROM Riwayat");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhRiwayatActionPerformed

    private void txtCariRiwayatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariRiwayatKeyReleased
        String c = txtCariRiwayat.getText();
        String cari = "SELECT*FROM Riwayat WHERE id LIKE '%"+c+"%'"+
                      "OR user_id LIKE '%"+c+"%' OR barang_id LIKE '%"+c+"%'"+
                      "OR jenis LIKE '%"+c+"%' OR tanggal LIKE '%"+c+"%'";
        mycode.tampilDataRiwayat(tabelRiwayat, cari);
    }//GEN-LAST:event_txtCariRiwayatKeyReleased

    private void btnHpsPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPesananActionPerformed
        try {
            mycode.hapusPesanan(txtIdPesanan.getText());
            mycode.tampilDataPesanan(tabelPesanan, "SELECT*FROM Pesanan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPesananActionPerformed

    private void btnSmpnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPesananActionPerformed
        try {
            if(txtIdPesanan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdPesanan.requestFocus();
            } else if(txtMarketingId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Marketing ID Belum Diisi");
                txtMarketingId.requestFocus();
            } else if(txtStafId.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Staf ID Belum Diisi");
                txtStafId.requestFocus();
            } else if(txtBarangId_Psn.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Barang ID Belum Diisi");
                txtBarangId_Psn.requestFocus();
            } else if(txtPermintaan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Permintaan Belum Diisi");
                txtPermintaan.requestFocus();
            } else if(txtPengiriman.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Pengiriman Belum Diisi");
                txtPengiriman.requestFocus();
            } else if(txtTanggalMinta.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Minta Belum Diisi");
                txtTanggalMinta.requestFocus();
            } else if(txtTanggalKirim.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Kirim Belum Diisi");
                txtTanggalKirim.requestFocus();
            } else if(txtStatusPesanan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusPesanan.requestFocus();
            } else if(txtRekomendasiPesanan.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Rekomendasi Belum Diisi");
                txtRekomendasiPesanan.requestFocus();
            } else if(txtStatusRekomendasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Rekomendasi Belum Diisi");
                txtStatusRekomendasi.requestFocus();
            } else {
                mycode.simpanPesanan02(txtIdPesanan.getText(), txtMarketingId.getText(),
                                       txtStafId.getText(), txtBarangId_Psn.getText(),
                                       txtPermintaan.getText(), txtPengiriman.getText(),
                                       txtTanggalMinta.getText(), txtTanggalKirim.getText(),
                                       txtStatusPesanan.getText(), txtRekomendasiPesanan.getText(),
                                       txtStatusRekomendasi.getText());

                mycode.tampilDataPesanan(tabelPesanan, "SELECT*FROM Pesanan");

                if (mycode.duplikasi == true){
                    txtMarketingId.setText(mycode.CEK_MARKETING_ID);
                    txtStafId.setText(mycode.CEK_STAF_ID);
                    txtBarangId_Psn.setText(mycode.CEK_BARANG_ID_PSN);
                    txtPermintaan.setText(mycode.CEK_PERMINTAAN);
                    txtPengiriman.setText(mycode.CEK_PENGIRIMAN);
                    txtTanggalMinta.setText(mycode.CEK_TANGGAL_MINTA);
                    txtTanggalKirim.setText(mycode.CEK_TANGGAL_KIRIM);
                    txtStatusPesanan.setText(mycode.CEK_STATUS_PSN);
                    txtRekomendasiPesanan.setText(mycode.CEK_REKOMENDASI_PSN);
                    txtStatusRekomendasi.setText(mycode.CEK_STATUS_REKOMENDASI);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPesananActionPerformed

    private void btnUbhPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPesananActionPerformed
        try {
                mycode.ubahPesanan(txtIdPesanan.getText(), txtMarketingId.getText(),
                                   txtStafId.getText(), txtBarangId_Psn.getText(),
                                   txtPermintaan.getText(), txtPengiriman.getText(),
                                   txtTanggalMinta.getText(), txtTanggalKirim.getText(),
                                   txtStatusPesanan.getText(), txtRekomendasiPesanan.getText(),
                                   txtStatusRekomendasi.getText());

                mycode.tampilDataPesanan(tabelPesanan, "SELECT*FROM Pesanan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPesananActionPerformed

    private void txtCariPesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPesananKeyReleased
        String c = txtCariPesanan.getText();
        String cari = "SELECT*FROM Pesanan WHERE id LIKE '%"+c+"%'"+
                      "OR marketing_id LIKE '%"+c+"%' OR staf_id LIKE '%"+c+"%'"+
                      "OR barang_id LIKE '%"+c+"%' OR status LIKE '%"+c+"%'"+
                      "OR tanggal_minta LIKE '%"+c+"%'";
        mycode.tampilDataPesanan(tabelPesanan, cari);
    }//GEN-LAST:event_txtCariPesananKeyReleased

    private void btnUbhBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhBarangActionPerformed
        try {
            mycode.ubahBarang(txtIdBarang.getText(), txtKodeBarang.getText(),
                              txtNamaBarang.getText(), txtKeteranganBarang.getText(),
                              txtStokAwal.getText(), txtStok.getText(),
                              txtSatuanId_Brg.getText(), txtRekomendasiBarang.getText(),
                              txtStatusBarang.getText(), txtAdminView.getText(),
                              txtStafView.getText(), txtTanggalUpdate.getText());

            mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhBarangActionPerformed

    private void btnSmpnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnBarangActionPerformed
        try {
            if(txtIdBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "ID Belum Diisi");
                txtIdBarang.requestFocus();
            } else if(txtKodeBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Kode Belum Diisi");
                txtKodeBarang.requestFocus();
            } else if(txtNamaBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaBarang.requestFocus();
            } else if(txtKeteranganBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKeteranganBarang.requestFocus();
            } else if(txtStokAwal.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Stok Awal Belum Diisi");
                txtStokAwal.requestFocus();
            } else if(txtStok.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Stok Belum Diisi");
                txtStok.requestFocus();
            } else if(txtSatuanId_Brg.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Satuan ID Belum Diisi");
                txtSatuanId_Brg.requestFocus();
            } else if(txtRekomendasiBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Rekomendasi Belum Diisi");
                txtRekomendasiBarang.requestFocus();
            } else if(txtStatusBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusBarang.requestFocus();
            } else if(txtAdminView.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Admin View Belum Diisi");
                txtAdminView.requestFocus();
            } else if(txtStafView.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Staf View Belum Diisi");
                txtStafView.requestFocus();
            } else if(txtTanggalUpdate.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Update Belum Diisi");
                txtTanggalUpdate.requestFocus();
            } else {
                mycode.simpanBarang02(txtIdBarang.getText(), txtKodeBarang.getText(),
                                      txtNamaBarang.getText(), txtKeteranganBarang.getText(),
                                      txtStokAwal.getText(), txtStok.getText(),
                                      txtSatuanId_Brg.getText(), txtRekomendasiBarang.getText(),
                                      txtStatusBarang.getText(), txtAdminView.getText(),
                                      txtStafView.getText(), txtTanggalUpdate.getText());

                mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang");

                if (mycode.duplikasi == true){
                    txtKodeBarang.setText(mycode.CEK_KODE_BRG);
                    txtNamaBarang.setText(mycode.CEK_NAMA_BRG);
                    txtKeteranganBarang.setText(mycode.CEK_KETERANGAN_BRG);
                    txtStokAwal.setText(mycode.CEK_STOK_AWAL);
                    txtStok.setText(mycode.CEK_STOK);
                    txtSatuanId_Brg.setText(mycode.CEK_SATUAN_ID);
                    txtRekomendasiBarang.setText(mycode.CEK_REKOMENDASI_BRG);
                    txtStatusBarang.setText(mycode.CEK_STATUS_BRG);
                    txtAdminView.setText(mycode.CEK_ADMIN_VIEW);
                    txtStafView.setText(mycode.CEK_STAF_VIEW);
                    txtTanggalUpdate.setText(mycode.CEK_TANGGAL_UPDATE);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnBarangActionPerformed

    private void btnHpsBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsBarangActionPerformed
        try {
            mycode.hapusBarang(txtIdBarang.getText());
            mycode.tampilDataBarang(tabelBarang, "SELECT*FROM barang");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsBarang;
    private javax.swing.JButton btnHpsPesanan;
    private javax.swing.JButton btnHpsRIwayat;
    private javax.swing.JButton btnHpsSatuan;
    private javax.swing.JButton btnPesanan;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnSatuan;
    private javax.swing.JButton btnSmpnBarang;
    private javax.swing.JButton btnSmpnPesanan;
    private javax.swing.JButton btnSmpnRiwayat;
    private javax.swing.JButton btnSmpnSatuan;
    private javax.swing.JButton btnUbhBarang;
    private javax.swing.JButton btnUbhPesanan;
    private javax.swing.JButton btnUbhRiwayat;
    private javax.swing.JButton btnUbhSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pnlBarang;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPesanan;
    private javax.swing.JPanel pnlRiwayat;
    private javax.swing.JPanel pnlSatuan;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTable tabelPesanan;
    private javax.swing.JTable tabelRiwayat;
    private javax.swing.JTable tabelSatuan;
    private javax.swing.JTextField txtAdminView;
    private javax.swing.JTextField txtBarangId_Psn;
    private javax.swing.JTextField txtBarangId_Rw;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtCariPesanan;
    private javax.swing.JTextField txtCariRiwayat;
    private javax.swing.JTextField txtCariSatuan;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtIdPesanan;
    private javax.swing.JTextField txtIdRiwayat;
    private javax.swing.JTextField txtIdSatuan;
    private javax.swing.JTextField txtJenisRiwayat;
    private javax.swing.JTextField txtKeteranganBarang;
    private javax.swing.JTextField txtKeteranganRiwayat;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKodeSatuan;
    private javax.swing.JTextField txtMarketingId;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaSatuan;
    private javax.swing.JTextField txtPengiriman;
    private javax.swing.JTextField txtPermintaan;
    private javax.swing.JTextField txtQtyRiwayat;
    private javax.swing.JTextField txtRekomendasiBarang;
    private javax.swing.JTextField txtRekomendasiPesanan;
    private javax.swing.JTextField txtSatuanId_Brg;
    private javax.swing.JTextField txtStafId;
    private javax.swing.JTextField txtStafView;
    private javax.swing.JTextField txtStatusBarang;
    private javax.swing.JTextField txtStatusPesanan;
    private javax.swing.JTextField txtStatusRekomendasi;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokAwal;
    private javax.swing.JTextField txtTanggalKirim;
    private javax.swing.JTextField txtTanggalMinta;
    private javax.swing.JTextField txtTanggalRiwayat;
    private javax.swing.JTextField txtTanggalUpdate;
    private javax.swing.JTextField txtUserId_Rw;
    // End of variables declaration//GEN-END:variables
}
